[tool.poetry]
name = "rivertils"
version = "0.1.13"
description = "utilities commonly used by rivers cuomo"
authors = ["Rivers Cuomo <riverscuomo@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
google-cloud-translate = "3.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
