[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "dataserver"
version = "1.0.1"
authors = [
  { name="Nguyen Minh Khoi", email="khoi.nguyenminh100912@gmail.com" },
]
description = "A free to use dataserver for everyone"
readme = "README.md"
requires-python = ">=3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/dataserver"
Issues = "https://github.com/pypa/dataserver/issues"