[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "djg"
version = "0.1.0"
authors = [
    {name="Domink Moos", email="dominik.moos@proton.me"}
]
description = "JSON generation based on schema."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
keywords = ["json", "json-schema", "json-generation"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Utilities",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = ["exrex"]

[tool.ruff]
line-length = 100
indent-width = 4

[tool.black]
line-length = 100
indent-width = 4
