[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"

[project]
name =  "material-color"
version = "1.0.0"
authors = [
    {name = "Martanto", email = "martanto@live.com"},
]
description = "Unofficial Android Material Color"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["material", "color", "android"]
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.0"
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
base = [
    "pandas"
]

[project.urls]
Homepage = "https://github.com/martanto/material-color"
Issues = "https://github.com/martanto/material-color/issues"