[tool.poetry]
name = "galadriel-node"
version = "0.0.1"
description = ""
authors = [
    "Kaspar Peterson <kaspar@galadriel.com>",
    "Kristjan Peterson <kristjan@galadriel.com>",
    "Kre≈°imir Grofelnik <kresimir@galadriel.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.12.3"
openai = "1.30.1"
requests = "2.31.0"
dataclasses-json = "^0.6.7"
websockets = "^13.0"

[tool.poetry.dev-dependencies]
black = "^24.8.0"
pytest = "^8.3.2"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
galadriel = "galadriel_node.cli.app:app"
