[project]
name = "koco-product-sqlmodel"
version = "0.1.1"
description = "Python module containing the SQLMODEL for the KOCO MOTION product description in the catalog database. Used import into the flask project and the later to define API-project"
authors = [
    { name = "Gerrit Kocherscheidt", email = "kochersg@koco-group.com" }
]
dependencies = [
    "sqlmodel>=0.0.21",
    "python-dotenv>=1.0.1",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/koco_product_sqlmodel"]
