[tool.poetry]
name = "pgbook"
version = "0.2.0"
description = "Pygame Function Book"
authors = ["zaiecunmin <zaiecunmin@qq.com>"]
readme = "README.md"
license = "Apache License"
packages = [
    { include = "pgbook"},
]

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^2.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
