[tool.poetry]
name = "contextforce-python"
version = "0.3.0"
description = ""
authors = ["developer <contextforce01@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
setuptools = "^72.1.0"
wheel = "^0.44.0"
twine = "^5.1.1"
pytest = "^8.3.2"
httpx = {extras = ["http2"], version = "^0.27.0"}


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
