[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
name = "tailx"
version = "0.0.2"
description = "tailx, 带颜色的 `tail -f`, 更好看的查看日志"
authors = [
    { name = "jiaosen", email = "jiaosenvip@163.com" },
    { name = "jiaosen" },
]
dependencies = [
    "rich",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/jiaosenvip/tailx"

[project.scripts]
tailx = "tailx:main"

[tool]
