[tool.poetry]
name = "pyoutlineapi"
version = "0.1.2"
description = "A Python package to interact with the Outline VPN Server API"
authors = ["Denis Rozhnovskiy <pytelemonbot@mail.ru>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "pyoutlineapi" }]

[tool.poetry.dependencies]
python = ">=3.10"
pydantic = "^2.0.0"
requests = "^2.32.3"
requests-toolbelt = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest-cov = "^5.0.0"

[tool.pytest.ini_options]
addopts = "--cov=pyoutlineapi --cov-report=term"

[tool.poetry.urls]
homepage = "https://github.com/orenlab/pyoutlineapi"
repository = "https://github.com/orenlab/pyoutlineapi"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
