[build-system]
requires = ["setuptools>=40.8.0","wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "jgtutils"
version = "0.2.174"
description = "A utility package common to other JGT projects."
readme = "README.md"
authors = [{ name = "Guillaume Isabelle", email = "jgi@jgwill.com" }]
license = { file = "LICENSE" }
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]
keywords = ["utilities"]

dependencies = [
	'tlid>=0.1.15',
  'ruamel.yaml>=0.18.6'
]

[project.urls]
"Homepage" = "https://github.com/jgwill/jgtutils"
"Bug Tracker" = "https://github.com/jgwill/jgtutils/issues"



[project.scripts]
jgtutr = "jgtutils.cli_tlid_range:main"
jgtset = "jgtutils.jgtset:main"
