[project]
authors = [
  {name = "Jonathan Dobson"},
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: MacOS :: MacOS X",
]
description = "Language Model Modules for appLM on Apple Silicon"
name = "applm-models"
readme = "README.md"
requires-python = ">=3.8"
version = "0.0.33"

[project.urls]
Homepage = "https://github.com/Jonathan-Dobson/applm-models"
Issues = "https://github.com/Jonathan-Dobson/applm-models/issues"

