[build-system]
requires = [
    "setuptools>=43.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "splg"
description = "Elderly, Handicapped, Criminals, Wicked"
version = "2"
authors = [
    {name = "Bart Thate", email = "bthate@dds.nl"},
]
readme = "README.rst"
license = {text="Public Domain"}
classifiers = [ 
    'Development Status :: 3 - Alpha',
    'License :: Public Domain',
    'Operating System :: Unix',
    'Programming Language :: Python',
    'Topic :: Utilities'
]


[project.scripts]
"splg"  = "splg.__main__:wrapped"
"splgc" = "splg.prompt:wrapped"
"splgd" = "splg.daemon:wrapped"


[project.urls]
"home" = "https://pypi.org/project/splg"
"bugs" = "https://github.com/bthate/splg/issues"
"source" = "https://github.com/bthate/splg"


[tool.setuptools]
packages = [
    'splg',
    'splg.modules'
]
zip-safe=true


[tool.setuptools.data-files]
"share/doc/splg" = [
    "README.rst",
]
[tool.setuptools.exclude-package-data]
"*" = [
       "env*",
       "html*",
       "test*"
      ]
