[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spectacular_analysis"
version = "0.0.5"
description = "Bayesian logistic regression modeling"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    {name = "Bradford Patton", email = "bradfordpatton72@gmail.com"},
    {name = "Alvin Dean Jeffrey ", email= "alvin.d.jeffery@vanderbilt.edu"},
    {name = "Dagmawi Negesse", email= "dagmawi.negesse@vanderbilt.edu"},
    {name = "Parker Christy", email= "parker.christy@vanderbilt.edu"},
    {name = "Satkar Dhakal", email= "satkar.dhakal@vanderbilt.edu"},
    {name = "Lara Khayatt", email= "lara.khayatt@vanderbilt.edu"},
]
maintainers = [
    { name = "Alvin Dean Jeffrey ", email= "alvin.d.jeffery@vanderbilt.edu" },
    { name = "Bradford Patton", email = "bradfordpatton72@gmail.com" },
    { name = "Dagmawi Negesse", email= "dagmawi.negesse@vanderbilt.edu"},
    { name = "Satkar Dhakal", email= "satkar.dhakal@vanderbilt.edu" },
]
keywords = ["Spectacular", "Bayesian Analysis","Logistic Regression"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

dependencies = [
    "pymc>=5.16.2",        
    "pandas",            
    "arviz",  
    "numpy",
    "numpy<2.0.0; sys_platform == 'win32'",
    "click",
    "click_default_group",
    "scikit-learn",
    "tqdm",
    "requests",
    "optuna>=2.0.0",
    "pandas>=1.0.0",
    "tabulate",
    "more_click",
    "more_itertools",
    "pystow>=0.4.3",
    "docdata",
    "class_resolver>0.4.2",
    "typing_extensions",
    "matplotlib",
    "matplotlib>=3.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include=["spectacular_analysis"]


[tool.setuptools]
package-dir = { "" = "src" }

[tool.cruft]
skip = [
    "**/__init__.py",
    "tests/*"
]

[tool.black]
line-length = 120
target-version = [
    "py39",
    "py310",
    "py311",
    "py312",
]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120

[tool.ruff]
line-length = 120
extend-include = ["*.ipynb"]

[project.urls]
"Bug Tracker" = "https://github.com/quantitativenurse/SPECTACULAR/issues"
Homepage = "https://github.com/quantitativenurse/SPECTACULAR"
Repository = "https://github.com/quantitativenurse/SPECTACULAR.git"
