[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "email_draft_generator"
version = "0.1.1"
description = "A utility to generate E-mail drafts from a list of E-mail addresses."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
keywords = ["email", "gmail", "email-template", "email-generator"]

# This should be your name or the name of the organization who originally authored the project, and a valid email address corresponding to the name listed.
authors = [
	{ name = "Brandon Clague", email = "94200657+fodfodfod@users.noreply.github.com" },
	{ name = "Max Nargang", email = "CoffeeCoder1@outlook.com" },
]

# This should be your name or the names of the organization who currently maintains the project, and a valid email address corresponding to the name listed.
maintainers = [{ name = "Max Nargang", email = "CoffeeCoder1@outlook.com" }]

# For a list of valid classifiers, see https://pypi.org/classifiers/
classifiers = [
	# How mature is this project? Common values are
	#   3 - Alpha
	#   4 - Beta
	#   5 - Production/Stable
	"Development Status :: 4 - Beta",
	"Intended Audience :: Customer Service",
	"Topic :: Communications :: Email :: Mailing List Servers",
	"License :: OSI Approved :: MIT License",
	"Programming Language :: Python :: 3",
]

dependencies = [
	"google-api-python-client",
	"google-auth-httplib2",
	"google-auth-oauthlib",
	"json-fix",
]

[project.optional-dependencies]
packaging = ["pyinstaller", "pillow"]

[project.urls]
"Homepage" = "https://github.com/CoffeeCoder1/Email-Generator"
"Bug Reports" = "https://github.com/CoffeeCoder1/Email-Generator/issues"
"Source" = "https://github.com/CoffeeCoder1/Email-Generator"

[project.scripts]
email-generator = "email_draft_generator.main:main"
email-list-parser = "email_draft_generator.file_parser.main:main"
email-generator-gui = "email_draft_generator.gui.main:main"
email-template-editor-gui = "email_draft_generator.gui.template_editor:main"
