[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "felesviz"
version = "0.2.5"
description = "Acciones para facilitar la vida de un cientÃ­fico de datos"
readme = "README.md"
authors = [{ name = "Miguel Feles"}]
license = { file = "LICENSE" }
 
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
keywords = ["Annotation"]
 
dependencies = [ "opencv-python", "natsort", ]
 
requires-python = ">=3.5"