[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "QuickRev"
version = "0.0.4"
authors = [
 { name="Isuagr239", email="Za1van@yandex.ru" },
]
description = "Reversing 2 variables"
readme = "README.md"
requires-python = ">=3.10.0"
classifiers = [
   "Programming Language :: Python :: 3",
   "License :: OSI Approved :: MIT License",
   "Operating System :: OS Independent",
]