[project]
name = "tunan_ground"
version = "0.0.4"
authors = [
  { name="wutunan", email="19970694323@163.com" },
]
description = "wutunan say hello"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
