[tool.poetry]
name = "LatinDeckCreator"
version = "0.0.3"
description = "A Latin flashcard deck creator"
authors = ["Forrest Zeng <ForrestZengMusic@gmail.com>"]
packages = [
    { include = "LatinDeckCreator" }
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"