[project]
name = "gpu_waiter"
version = "0.0.4"
description = "gpu device moniter and automaticly run commond if device available, just for nvidia gpu."
readme = "README.md"
authors = [{name = "lijunjie2232", email = "2533584225@qq.com"}]
maintainers  = [{name = "lijunjie2232", email = "2533584225@qq.com"}]
dependencies = [
    "nvitop",
]

[project.urls]
Homepage = "https://pypi.org/project/gpu-waiter"
Repository = "https://github.com/lijunjie2232/gpu_waiter.git"
Issues = "https://github.com/lijunjie2232/gpu_waiter/issues"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pylint.design]
max-line-length = 120

[tool.setuptools.exclude-package-data]
pypackage = ["device/*.txt"]

[project.scripts]
waiter = "gpu_waiter.main:main"
