[tool.poetry]
name = "mjooln"
version = "0.8.2"
description = "File handling for Data Engineers"
authors = ["Vemund Halm√∏ Aarstrand <vemundaa@gmail.com>"]
readme = "README"
homepage = "https://mjooln.readthedocs.org"
repository = "https://gitlab.com/vemundaa/mjooln"
documentation = "https://mjooln.readthedocs.org"
license = "MIT"
keywords = ['json', 'path', 'file', 'folder', 'file handling',
    'encryption', 'compression', 'aes', 'gzip', 'uuid', 'utc',
    'md5 checksum', 'data engineer', 'data science', 'data lake',
    'microservice']

[tool.poetry.dependencies]
python = "^3.9"
pyyaml = "^6.0"
python-dateutil = "^2.8.2"
pytz = "^2024"
cryptography = "^43"
simplejson = "^3.18.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
numpy = "^1.26.4"
pandas = "^2.2.2"
pytest = "^8.3.2"
mypy = "^1.11.2"
ruff = "^0.6.3"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.0.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
numpy = "^1.26.4"
pandas = "^2.2.2"
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = ["E", "F", "W", "UP", "I"]
lint.ignore = ["F403"]
line-length = 120
exclude = ["experimental"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = true

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.mypy]
exclude = ["experimental"]